name: Backend Tests

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore NuGet packages
        run: dotnet restore BackendTests/BackendTests.csproj

      - name: Build project
        run: dotnet build --configuration Release BackendTests/BackendTests.csproj

      - name: Run tests
        run: command dotnet test BackendTests/BackendTests.csproj
